spring.datasource.url=jdbc:mysql://localhost:3306/diagnocare_hdms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajendnam333@gmail.com
spring.mail.password=rolaptkzrhscftvx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
razorpay.key.id=rzp_test_SPyM8SIbKPjISv
razorpay.key.secret=cOK8tIu9YCZQa8SEg4jX9Njx
groq.api.key=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